name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t mcarolan/gopds-docker:latest .

      - name: Push to Docker Hub
        run: docker push mcarolan/gopds-docker:latest
